// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7JxgzYSW8MJ4XhJECM8EYC6r1x4uWX0w',
    appId: '1:685145175490:web:32d989517692f198f7125b',
    messagingSenderId: '685145175490',
    projectId: 'cetep-87b28',
    authDomain: 'cetep-87b28.firebaseapp.com',
    storageBucket: 'cetep-87b28.appspot.com',
    measurementId: 'G-HWJEMD6ENY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDbw-sR-XD7XlCeiIZkDJhMMRfqfepctE',
    appId: '1:685145175490:android:b0e563acec3a0f2ef7125b',
    messagingSenderId: '685145175490',
    projectId: 'cetep-87b28',
    storageBucket: 'cetep-87b28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnlUrEgmKLfi4NOQU8u4GG7A2ZC0UMCmE',
    appId: '1:685145175490:ios:1835593717457341f7125b',
    messagingSenderId: '685145175490',
    projectId: 'cetep-87b28',
    storageBucket: 'cetep-87b28.appspot.com',
    iosBundleId: 'com.ggwp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnlUrEgmKLfi4NOQU8u4GG7A2ZC0UMCmE',
    appId: '1:685145175490:ios:1835593717457341f7125b',
    messagingSenderId: '685145175490',
    projectId: 'cetep-87b28',
    storageBucket: 'cetep-87b28.appspot.com',
    iosBundleId: 'com.ggwp.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7JxgzYSW8MJ4XhJECM8EYC6r1x4uWX0w',
    appId: '1:685145175490:web:5752339e9588e026f7125b',
    messagingSenderId: '685145175490',
    projectId: 'cetep-87b28',
    authDomain: 'cetep-87b28.firebaseapp.com',
    storageBucket: 'cetep-87b28.appspot.com',
    measurementId: 'G-CJLCJKZHPG',
  );
}
